security:
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false
            anonymous: ~

        secured_area:
            pattern:    ^/admin
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /admin/issue
            logout:
                path: /admin/logout
                target: /issue

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: /.*, role: ROLE_USER }

    providers:
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext